
logging:
  version: 1
  formatters:
    formatter:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
  handlers:
    console:
      class: "logging.StreamHandler"
      level: "DEBUG"
      formatter: "formatter"
      stream: "ext://sys.stderr"
  root:
    handlers: ["console"]
  loggers:
    animotion:
      level: "INFO"

camera:
  horizontal_flip: false
  vertical_flip: false

  video:
    resolution: [1280, 720]
    format: "RGB888"
    encoder: "H264"
    bitrate: 1000000
    quality: "medium"

  preview:
    resolution: [320, 240]
    format: "YUV420"

trigger:
  threshold: 7
  delay_in_seconds: 2

app:
  video_target_folder: "/tmp/"
  image_target_folder: "/tmp/"
  image_interval_in_seconds: 2
  image_format: "jpg"
